// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcekraixvaxumbntdiau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjZWtyYWl4dmF4dW1ibnRkaWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MjgwNzQsImV4cCI6MjA1NDIwNDA3NH0.nCTRg5qV4PBjOc98jS_pzk4ntriBlk7Rf2j-QeZpYk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);